
package org.ogf.schemas.nsi._2013._12.connection._interface;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.4
 * 2014-02-18T11:21:07.287+01:00
 * Generated source version: 2.7.4
 */

@WebFault(name = "error", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types")
public class Error extends Exception {
    
    private org.ogf.schemas.nsi._2013._12.connection.types.GenericErrorType error;

    public Error() {
        super();
    }
    
    public Error(String message) {
        super(message);
    }
    
    public Error(String message, Throwable cause) {
        super(message, cause);
    }

    public Error(String message, org.ogf.schemas.nsi._2013._12.connection.types.GenericErrorType error) {
        super(message);
        this.error = error;
    }

    public Error(String message, org.ogf.schemas.nsi._2013._12.connection.types.GenericErrorType error, Throwable cause) {
        super(message, cause);
        this.error = error;
    }

    public org.ogf.schemas.nsi._2013._12.connection.types.GenericErrorType getFaultInfo() {
        return this.error;
    }
}
