
package org.ogf.schemas.nsi._2013._12.connection._interface;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.4
 * 2014-02-18T11:21:11.588+01:00
 * Generated source version: 2.7.4
 */

@WebFault(name = "serviceException", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types")
public class ServiceException extends Exception {
    
    private org.ogf.schemas.nsi._2013._12.framework.types.ServiceExceptionType serviceException;

    public ServiceException() {
        super();
    }
    
    public ServiceException(String message) {
        super(message);
    }
    
    public ServiceException(String message, Throwable cause) {
        super(message, cause);
    }

    public ServiceException(String message, org.ogf.schemas.nsi._2013._12.framework.types.ServiceExceptionType serviceException) {
        super(message);
        this.serviceException = serviceException;
    }

    public ServiceException(String message, org.ogf.schemas.nsi._2013._12.framework.types.ServiceExceptionType serviceException, Throwable cause) {
        super(message, cause);
        this.serviceException = serviceException;
    }

    public org.ogf.schemas.nsi._2013._12.framework.types.ServiceExceptionType getFaultInfo() {
        return this.serviceException;
    }
}
