package org.ogf.schemas.nsi._2013._12.connection.requester;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2014-02-18T11:21:11.664+01:00
 * Generated source version: 2.7.4
 * 
 */
@WebService(targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/requester", name = "ConnectionRequesterPort")
@XmlSeeAlso({org.ogf.schemas.nsi._2013._12.framework.headers.ObjectFactory.class, org.ogf.schemas.nsi._2013._12.connection.types.ObjectFactory.class, oasis.names.tc.saml._2_0.assertion.ObjectFactory.class, org.w3._2001._04.xmlenc.ObjectFactory.class, org.w3._2000._09.xmldsig.ObjectFactory.class, org.ogf.schemas.nsi._2013._12.framework.types.ObjectFactory.class})
public interface ConnectionRequesterPort {

    /**
     * An autonomous error message issued from a Provider NSA to Requester
     * NSA.  The acknowledgment indicates that the Requester NSA has
     * accepted the notification request for processing. There are no
     * associated confirmed or failed messages.
     *             
     */
    @RequestWrapper(localName = "errorEvent", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.ErrorEventType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/12/connection/service/errorEvent")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.GenericAcknowledgmentType")
    public void errorEvent(
        @WebParam(name = "connectionId", targetNamespace = "")
        java.lang.String connectionId,
        @WebParam(name = "notificationId", targetNamespace = "")
        long notificationId,
        @WebParam(name = "timeStamp", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar timeStamp,
        @WebParam(name = "event", targetNamespace = "")
        org.ogf.schemas.nsi._2013._12.connection.types.EventEnumType event,
        @WebParam(name = "originatingConnectionId", targetNamespace = "")
        java.lang.String originatingConnectionId,
        @WebParam(name = "originatingNSA", targetNamespace = "")
        java.lang.String originatingNSA,
        @WebParam(name = "additionalInfo", targetNamespace = "")
        org.ogf.schemas.nsi._2013._12.framework.types.TypeValuePairListType additionalInfo,
        @WebParam(name = "serviceException", targetNamespace = "")
        org.ogf.schemas.nsi._2013._12.framework.types.ServiceExceptionType serviceException,
        @WebParam(mode = WebParam.Mode.INOUT, name = "nsiHeader", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/framework/headers", header = true)
        javax.xml.ws.Holder<org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType> header
    ) throws org.ogf.schemas.nsi._2013._12.connection._interface.ServiceException;

    /**
     * This queryResultConfirmed message is sent from the Provider NSA to
     * Requester NSA as an indication of a successful queryResult operation.
     * This is in response to an original queryResult request from the
     * associated Requester NSA.
     *             
     */
    @RequestWrapper(localName = "queryResultConfirmed", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.QueryResultConfirmedType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/12/connection/service/queryResultConfirmed")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.GenericAcknowledgmentType")
    public void queryResultConfirmed(
        @WebParam(name = "result", targetNamespace = "")
        java.util.List<org.ogf.schemas.nsi._2013._12.connection.types.QueryResultResponseType> result,
        @WebParam(mode = WebParam.Mode.INOUT, name = "nsiHeader", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/framework/headers", header = true)
        javax.xml.ws.Holder<org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType> header
    ) throws org.ogf.schemas.nsi._2013._12.connection._interface.ServiceException;

    /**
     * This reserveAbortConfirmed message is sent from a Provider NSA to
     * Requester NSA as an indication of a successful reserveAbort.
     * This is in response to an original reserveAbort request from the
     * associated Requester NSA.
     *             
     */
    @RequestWrapper(localName = "reserveAbortConfirmed", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.GenericConfirmedType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/12/connection/service/reserveAbortConfirmed")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.GenericAcknowledgmentType")
    public void reserveAbortConfirmed(
        @WebParam(name = "connectionId", targetNamespace = "")
        java.lang.String connectionId,
        @WebParam(mode = WebParam.Mode.INOUT, name = "nsiHeader", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/framework/headers", header = true)
        javax.xml.ws.Holder<org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType> header
    ) throws org.ogf.schemas.nsi._2013._12.connection._interface.ServiceException;

    /**
     * This reserveFailed message is sent from a Provider NSA to
     * Requester NSA as an indication of a reserve failure. This
     * is in response to an original reserve request from the
     * associated Requester NSA.
     *             
     */
    @RequestWrapper(localName = "reserveFailed", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.GenericFailedType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/12/connection/service/reserveFailed")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.GenericAcknowledgmentType")
    public void reserveFailed(
        @WebParam(name = "connectionId", targetNamespace = "")
        java.lang.String connectionId,
        @WebParam(name = "connectionStates", targetNamespace = "")
        org.ogf.schemas.nsi._2013._12.connection.types.ConnectionStatesType connectionStates,
        @WebParam(name = "serviceException", targetNamespace = "")
        org.ogf.schemas.nsi._2013._12.framework.types.ServiceExceptionType serviceException,
        @WebParam(mode = WebParam.Mode.INOUT, name = "nsiHeader", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/framework/headers", header = true)
        javax.xml.ws.Holder<org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType> header
    ) throws org.ogf.schemas.nsi._2013._12.connection._interface.ServiceException;

    /**
     * An autonomous message issued from a Provider NSA to Requester
     * NSA.  The acknowledgment indicates that the Requester NSA has
     * accepted the notification request for processing. There are no
     * associated confirmed or failed messages.
     *             
     */
    @RequestWrapper(localName = "messageDeliveryTimeout", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.MessageDeliveryTimeoutRequestType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/12/connection/service/messageDeliveryTimeout")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.GenericAcknowledgmentType")
    public void messageDeliveryTimeout(
        @WebParam(name = "connectionId", targetNamespace = "")
        java.lang.String connectionId,
        @WebParam(name = "notificationId", targetNamespace = "")
        long notificationId,
        @WebParam(name = "timeStamp", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar timeStamp,
        @WebParam(name = "correlationId", targetNamespace = "")
        java.lang.String correlationId,
        @WebParam(mode = WebParam.Mode.INOUT, name = "nsiHeader", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/framework/headers", header = true)
        javax.xml.ws.Holder<org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType> header
    ) throws org.ogf.schemas.nsi._2013._12.connection._interface.ServiceException;

    /**
     * This reserveConfirmed message is sent from a Provider NSA to
     * Requester NSA as an indication of a successful reservation. This
     * is in response to an original reserve request from the
     * associated Requester NSA.
     *             
     */
    @RequestWrapper(localName = "reserveConfirmed", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.ReserveConfirmedType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/12/connection/service/reserveConfirmed")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.GenericAcknowledgmentType")
    public void reserveConfirmed(
        @WebParam(name = "connectionId", targetNamespace = "")
        java.lang.String connectionId,
        @WebParam(name = "globalReservationId", targetNamespace = "")
        java.lang.String globalReservationId,
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description,
        @WebParam(name = "criteria", targetNamespace = "")
        org.ogf.schemas.nsi._2013._12.connection.types.ReservationConfirmCriteriaType criteria,
        @WebParam(mode = WebParam.Mode.INOUT, name = "nsiHeader", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/framework/headers", header = true)
        javax.xml.ws.Holder<org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType> header
    ) throws org.ogf.schemas.nsi._2013._12.connection._interface.ServiceException;

    /**
     * An autonomous message issued from a Provider NSA to Requester
     * NSA.  The acknowledgment indicates that the Requester NSA has
     * accepted the notification request for processing. There are no
     * associated confirmed or failed messages.
     *             
     */
    @RequestWrapper(localName = "dataPlaneStateChange", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.DataPlaneStateChangeRequestType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/12/connection/service/dataPlaneStateChange")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.GenericAcknowledgmentType")
    public void dataPlaneStateChange(
        @WebParam(name = "connectionId", targetNamespace = "")
        java.lang.String connectionId,
        @WebParam(name = "notificationId", targetNamespace = "")
        long notificationId,
        @WebParam(name = "timeStamp", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar timeStamp,
        @WebParam(name = "dataPlaneStatus", targetNamespace = "")
        org.ogf.schemas.nsi._2013._12.connection.types.DataPlaneStatusType dataPlaneStatus,
        @WebParam(mode = WebParam.Mode.INOUT, name = "nsiHeader", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/framework/headers", header = true)
        javax.xml.ws.Holder<org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType> header
    ) throws org.ogf.schemas.nsi._2013._12.connection._interface.ServiceException;

    /**
     * An autonomous message issued from a Provider NSA to Requester
     * NSA.  The acknowledgment indicates that the Requester NSA has
     * accepted the notification request for processing. There are no
     * associated confirmed or failed messages.
     *             
     */
    @RequestWrapper(localName = "reserveTimeout", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.ReserveTimeoutRequestType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/12/connection/service/reserveTimeout")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.GenericAcknowledgmentType")
    public void reserveTimeout(
        @WebParam(name = "connectionId", targetNamespace = "")
        java.lang.String connectionId,
        @WebParam(name = "notificationId", targetNamespace = "")
        long notificationId,
        @WebParam(name = "timeStamp", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar timeStamp,
        @WebParam(name = "timeoutValue", targetNamespace = "")
        int timeoutValue,
        @WebParam(name = "originatingConnectionId", targetNamespace = "")
        java.lang.String originatingConnectionId,
        @WebParam(name = "originatingNSA", targetNamespace = "")
        java.lang.String originatingNSA,
        @WebParam(mode = WebParam.Mode.INOUT, name = "nsiHeader", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/framework/headers", header = true)
        javax.xml.ws.Holder<org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType> header
    ) throws org.ogf.schemas.nsi._2013._12.connection._interface.ServiceException;

    /**
     * This releaseConfirmed message is sent from a Provider NSA to
     * Requester NSA as an indication of a successful release operation.
     * This is in response to an original release request from the
     * associated Requester NSA.
     *             
     */
    @RequestWrapper(localName = "releaseConfirmed", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.GenericConfirmedType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/12/connection/service/releaseConfirmed")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.GenericAcknowledgmentType")
    public void releaseConfirmed(
        @WebParam(name = "connectionId", targetNamespace = "")
        java.lang.String connectionId,
        @WebParam(mode = WebParam.Mode.INOUT, name = "nsiHeader", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/framework/headers", header = true)
        javax.xml.ws.Holder<org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType> header
    ) throws org.ogf.schemas.nsi._2013._12.connection._interface.ServiceException;

    /**
     * This reserveCommitConfirmed message is sent from a Provider NSA to
     * Requester NSA as an indication of a successful reserveCommit request.
     * This is in response to an original reserveCommit request from the
     * associated Requester NSA.
     *             
     */
    @RequestWrapper(localName = "reserveCommitConfirmed", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.GenericConfirmedType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/12/connection/service/reserveCommitConfirmed")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.GenericAcknowledgmentType")
    public void reserveCommitConfirmed(
        @WebParam(name = "connectionId", targetNamespace = "")
        java.lang.String connectionId,
        @WebParam(mode = WebParam.Mode.INOUT, name = "nsiHeader", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/framework/headers", header = true)
        javax.xml.ws.Holder<org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType> header
    ) throws org.ogf.schemas.nsi._2013._12.connection._interface.ServiceException;

    /**
     * This reserveCommitFailed message is sent from a Provider NSA to
     * Requester NSA as an indication of a modify failure. This
     * is in response to an original modify request from the
     * associated Requester NSA.
     *             
     */
    @RequestWrapper(localName = "reserveCommitFailed", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.GenericFailedType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/12/connection/service/reserveCommitFailed")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.GenericAcknowledgmentType")
    public void reserveCommitFailed(
        @WebParam(name = "connectionId", targetNamespace = "")
        java.lang.String connectionId,
        @WebParam(name = "connectionStates", targetNamespace = "")
        org.ogf.schemas.nsi._2013._12.connection.types.ConnectionStatesType connectionStates,
        @WebParam(name = "serviceException", targetNamespace = "")
        org.ogf.schemas.nsi._2013._12.framework.types.ServiceExceptionType serviceException,
        @WebParam(mode = WebParam.Mode.INOUT, name = "nsiHeader", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/framework/headers", header = true)
        javax.xml.ws.Holder<org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType> header
    ) throws org.ogf.schemas.nsi._2013._12.connection._interface.ServiceException;

    /**
     * This queryNotificationConfirmed message is sent from the Provider NSA to
     * Requester NSA as an indication of a successful queryNotification
     * operation. This is in response to an original queryNotification request
     * from the associated Requester NSA.
     *             
     */
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", partName = "acknowledgment")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/12/connection/service/queryNotificationConfirmed")
    public org.ogf.schemas.nsi._2013._12.connection.types.GenericAcknowledgmentType queryNotificationConfirmed(
        @WebParam(partName = "queryNotificationConfirmed", name = "queryNotificationConfirmed", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types")
        org.ogf.schemas.nsi._2013._12.connection.types.QueryNotificationConfirmedType queryNotificationConfirmed,
        @WebParam(partName = "header", mode = WebParam.Mode.INOUT, name = "nsiHeader", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/framework/headers", header = true)
        javax.xml.ws.Holder<org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType> header
    ) throws org.ogf.schemas.nsi._2013._12.connection._interface.ServiceException;

    /**
     * The error message is sent from a Provider NSA to Requester
     * NSA as an indication of the occurence of an error condition.
     * This  is in response to an original request from the associated
     * Requester NSA.
     *             
     */
    @RequestWrapper(localName = "error", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.GenericErrorType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/12/connection/service/error")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.GenericAcknowledgmentType")
    public void error(
        @WebParam(name = "serviceException", targetNamespace = "")
        org.ogf.schemas.nsi._2013._12.framework.types.ServiceExceptionType serviceException,
        @WebParam(mode = WebParam.Mode.INOUT, name = "nsiHeader", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/framework/headers", header = true)
        javax.xml.ws.Holder<org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType> header
    ) throws org.ogf.schemas.nsi._2013._12.connection._interface.ServiceException;

    /**
     * This terminateConfirmed message is sent from a Provider NSA to
     * Requester NSA as an indication of a successful terminate operation.
     * This is in response to an original terminate request from the
     * associated Requester NSA.
     *             
     */
    @RequestWrapper(localName = "terminateConfirmed", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.GenericConfirmedType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/12/connection/service/terminateConfirmed")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.GenericAcknowledgmentType")
    public void terminateConfirmed(
        @WebParam(name = "connectionId", targetNamespace = "")
        java.lang.String connectionId,
        @WebParam(mode = WebParam.Mode.INOUT, name = "nsiHeader", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/framework/headers", header = true)
        javax.xml.ws.Holder<org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType> header
    ) throws org.ogf.schemas.nsi._2013._12.connection._interface.ServiceException;

    /**
     * This querySummaryConfirmed message is sent from the target NSA to
     * requesting NSA as an indication of a successful querySummary
     * operation. This is in response to an original querySummary request
     * from the associated Requester NSA.
     *             
     */
    @RequestWrapper(localName = "querySummaryConfirmed", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.QuerySummaryConfirmedType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/12/connection/service/querySummaryConfirmed")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.GenericAcknowledgmentType")
    public void querySummaryConfirmed(
        @WebParam(name = "reservation", targetNamespace = "")
        java.util.List<org.ogf.schemas.nsi._2013._12.connection.types.QuerySummaryResultType> reservation,
        @WebParam(mode = WebParam.Mode.INOUT, name = "nsiHeader", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/framework/headers", header = true)
        javax.xml.ws.Holder<org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType> header
    ) throws org.ogf.schemas.nsi._2013._12.connection._interface.ServiceException;

    /**
     * This provisionConfirmed message is sent from a Provider NSA to
     * Requester NSA as an indication of a successful provision operation.
     * This is in response to an original provision request from the
     * associated Requester NSA.
     *             
     */
    @RequestWrapper(localName = "provisionConfirmed", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.GenericConfirmedType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/12/connection/service/provisionConfirmed")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.GenericAcknowledgmentType")
    public void provisionConfirmed(
        @WebParam(name = "connectionId", targetNamespace = "")
        java.lang.String connectionId,
        @WebParam(mode = WebParam.Mode.INOUT, name = "nsiHeader", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/framework/headers", header = true)
        javax.xml.ws.Holder<org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType> header
    ) throws org.ogf.schemas.nsi._2013._12.connection._interface.ServiceException;

    /**
     * This queryRecursiveConfirmed message is sent from the Provider NSA to
     * Requester NSA as an indication of a successful queryRecursive
     * operation. This is in response to an original queryRecursive request
     * from the associated Requester NSA.
     *             
     */
    @RequestWrapper(localName = "queryRecursiveConfirmed", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.QueryRecursiveConfirmedType")
    @WebMethod(action = "http://schemas.ogf.org/nsi/2013/12/connection/service/queryRecursiveConfirmed")
    @ResponseWrapper(localName = "acknowledgment", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/types", className = "org.ogf.schemas.nsi._2013._12.connection.types.GenericAcknowledgmentType")
    public void queryRecursiveConfirmed(
        @WebParam(name = "reservation", targetNamespace = "")
        java.util.List<org.ogf.schemas.nsi._2013._12.connection.types.QueryRecursiveResultType> reservation,
        @WebParam(mode = WebParam.Mode.INOUT, name = "nsiHeader", targetNamespace = "http://schemas.ogf.org/nsi/2013/12/framework/headers", header = true)
        javax.xml.ws.Holder<org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType> header
    ) throws org.ogf.schemas.nsi._2013._12.connection._interface.ServiceException;
}
