
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.ogf.schemas.nsi._2013._12.connection.provider;

import net.geant.nsicontest.reservation.Coordinator;

import org.ogf.schemas.nsi._2013._12.connection.types.GenericAcknowledgmentType;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2014-02-18T11:21:07.363+01:00
 * Generated source version: 2.7.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "ConnectionServiceProvider",
                      portName = "ConnectionServiceProviderPort",
                      targetNamespace = "http://schemas.ogf.org/nsi/2013/12/connection/provider",
                      wsdlLocation = "file:etc/wsdl/ConnectionService/ogf_nsi_connection_provider_v2_0.wsdl",
                      endpointInterface = "org.ogf.schemas.nsi._2013._12.connection.provider.ConnectionProviderPort")
                      
public class ConnectionProviderPortImpl implements ConnectionProviderPort {

    /* (non-Javadoc)
     * @see org.ogf.schemas.nsi._2013._12.connection.provider.ConnectionProviderPort#queryResultSync(java.lang.String  connectionId ,)java.lang.Long  startResultId ,)java.lang.Long  endResultId ,)org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType  header )*
     */
    public java.util.List<org.ogf.schemas.nsi._2013._12.connection.types.QueryResultResponseType> queryResultSync(java.lang.String connectionId,java.lang.Long startResultId,java.lang.Long endResultId,javax.xml.ws.Holder<org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType> header) throws org.ogf.schemas.nsi._2013._12.connection._interface.Error    {
    	
    	return Coordinator.queryResultSync(header, connectionId, startResultId, endResultId);
    }

    /* (non-Javadoc)
     * @see org.ogf.schemas.nsi._2013._12.connection.provider.ConnectionProviderPort#querySummary(org.ogf.schemas.nsi._2013._12.connection.types.QueryType  querySummary ,)org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType  header )*
     */
    public org.ogf.schemas.nsi._2013._12.connection.types.GenericAcknowledgmentType querySummary(org.ogf.schemas.nsi._2013._12.connection.types.QueryType querySummary,javax.xml.ws.Holder<org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType> header) throws org.ogf.schemas.nsi._2013._12.connection._interface.ServiceException    { 
        
    	Coordinator.querySummary(header, querySummary);
    	return new GenericAcknowledgmentType();
    }

    /* (non-Javadoc)
     * @see org.ogf.schemas.nsi._2013._12.connection.provider.ConnectionProviderPort#provision(java.lang.String  connectionId ,)org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType  header )*
     */
    public void provision(java.lang.String connectionId,javax.xml.ws.Holder<org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType> header) throws org.ogf.schemas.nsi._2013._12.connection._interface.ServiceException    { 

    	Coordinator.provision(header, connectionId);
    }

    /* (non-Javadoc)
     * @see org.ogf.schemas.nsi._2013._12.connection.provider.ConnectionProviderPort#terminate(java.lang.String  connectionId ,)org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType  header )*
     */
    public void terminate(java.lang.String connectionId,javax.xml.ws.Holder<org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType> header) throws org.ogf.schemas.nsi._2013._12.connection._interface.ServiceException    { 

    	Coordinator.terminate(header, connectionId);
    }

    /* (non-Javadoc)
     * @see org.ogf.schemas.nsi._2013._12.connection.provider.ConnectionProviderPort#release(java.lang.String  connectionId ,)org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType  header )*
     */
    public void release(java.lang.String connectionId,javax.xml.ws.Holder<org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType> header) throws org.ogf.schemas.nsi._2013._12.connection._interface.ServiceException    { 
        
        Coordinator.release(header, connectionId);
    }

    /* (non-Javadoc)
     * @see org.ogf.schemas.nsi._2013._12.connection.provider.ConnectionProviderPort#reserveAbort(java.lang.String  connectionId ,)org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType  header )*
     */
    public void reserveAbort(java.lang.String connectionId,javax.xml.ws.Holder<org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType> header) throws org.ogf.schemas.nsi._2013._12.connection._interface.ServiceException    { 
        
    	Coordinator.reserveAbort(header, connectionId);
    }

    /* (non-Javadoc)
     * @see org.ogf.schemas.nsi._2013._12.connection.provider.ConnectionProviderPort#reserveCommit(java.lang.String  connectionId ,)org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType  header )*
     */
    public void reserveCommit(java.lang.String connectionId,javax.xml.ws.Holder<org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType> header) throws org.ogf.schemas.nsi._2013._12.connection._interface.ServiceException    { 
        
    	Coordinator.reserveCommit(header, connectionId);
    }

    /* (non-Javadoc)
     * @see org.ogf.schemas.nsi._2013._12.connection.provider.ConnectionProviderPort#queryRecursive(org.ogf.schemas.nsi._2013._12.connection.types.QueryType  queryRecursive ,)org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType  header )*
     */
    public org.ogf.schemas.nsi._2013._12.connection.types.GenericAcknowledgmentType queryRecursive(org.ogf.schemas.nsi._2013._12.connection.types.QueryType queryRecursive,javax.xml.ws.Holder<org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType> header) throws org.ogf.schemas.nsi._2013._12.connection._interface.ServiceException    { 
        
    	Coordinator.queryRecursive(header, queryRecursive);
    	return new GenericAcknowledgmentType();
    }

    /* (non-Javadoc)
     * @see org.ogf.schemas.nsi._2013._12.connection.provider.ConnectionProviderPort#reserve(java.lang.String  connectionId ,)java.lang.String  globalReservationId ,)java.lang.String  description ,)org.ogf.schemas.nsi._2013._12.connection.types.ReservationRequestCriteriaType  criteria ,)org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType  header )*
     */
    public void reserve(javax.xml.ws.Holder<java.lang.String> connectionId,java.lang.String globalReservationId,java.lang.String description,org.ogf.schemas.nsi._2013._12.connection.types.ReservationRequestCriteriaType criteria,javax.xml.ws.Holder<org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType> header) throws org.ogf.schemas.nsi._2013._12.connection._interface.ServiceException    { 
            	
    	Coordinator.reserve(header, connectionId, globalReservationId, description, criteria);
    }

    /* (non-Javadoc)
     * @see org.ogf.schemas.nsi._2013._12.connection.provider.ConnectionProviderPort#queryNotificationSync(org.ogf.schemas.nsi._2013._12.connection.types.QueryNotificationType  queryNotificationSync ,)org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType  header )*
     */
    public org.ogf.schemas.nsi._2013._12.connection.types.QueryNotificationConfirmedType queryNotificationSync(org.ogf.schemas.nsi._2013._12.connection.types.QueryNotificationType queryNotificationSync,javax.xml.ws.Holder<org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType> header) throws org.ogf.schemas.nsi._2013._12.connection._interface.Error    { 
        
    	return Coordinator.queryNotificationSync(header, queryNotificationSync);
    }

    /* (non-Javadoc)
     * @see org.ogf.schemas.nsi._2013._12.connection.provider.ConnectionProviderPort#queryNotification(java.lang.String  connectionId ,)java.lang.Long  startNotificationId ,)java.lang.Long  endNotificationId ,)org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType  header )*
     */
    public void queryNotification(java.lang.String connectionId,java.lang.Long startNotificationId,java.lang.Long endNotificationId,javax.xml.ws.Holder<org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType> header) throws org.ogf.schemas.nsi._2013._12.connection._interface.ServiceException    { 
        
    	Coordinator.queryNotification(header, connectionId, startNotificationId, endNotificationId);
    }

    /* (non-Javadoc)
     * @see org.ogf.schemas.nsi._2013._12.connection.provider.ConnectionProviderPort#querySummarySync(org.ogf.schemas.nsi._2013._12.connection.types.QueryType  querySummarySync ,)org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType  header )*
     */
    public org.ogf.schemas.nsi._2013._12.connection.types.QuerySummaryConfirmedType querySummarySync(org.ogf.schemas.nsi._2013._12.connection.types.QueryType querySummarySync,javax.xml.ws.Holder<org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType> header) throws org.ogf.schemas.nsi._2013._12.connection._interface.Error    { 
        
    	return Coordinator.querySummarySync(header, querySummarySync);
    }

    /* (non-Javadoc)
     * @see org.ogf.schemas.nsi._2013._12.connection.provider.ConnectionProviderPort#queryResult(java.lang.String  connectionId ,)java.lang.Long  startResultId ,)java.lang.Long  endResultId ,)org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType  header )*
     */
    public void queryResult(java.lang.String connectionId,java.lang.Long startResultId,java.lang.Long endResultId,javax.xml.ws.Holder<org.ogf.schemas.nsi._2013._12.framework.headers.CommonHeaderType> header) throws org.ogf.schemas.nsi._2013._12.connection._interface.ServiceException    { 
        
    	Coordinator.queryResult(header, connectionId, startResultId, endResultId);
    }
}
